meta:
  engine: 4.0.4
  name: Zuuzboard
  version: 0.3
  author: Deon
  url: https://github.com/soundmonster/samoklava
units:
  kx: cx
  ky: cy
  px: 2
  py: 2
points:
  key:
    footprints:
      choc_hotswap:
        type: choc
        params:
          hotswap: true
          reverse: true
          keycaps: true
        nets:
          from: =column_net
          to: =row_net
  zones:
    matrix:
      key.padding: ky
      columns:
        pinky:
          key:
            stagger: 0 ky
            spread: kx
            splay: 10
          rows:
            bottom:
              row_net: row6
              column_net: col1
            home:
              row_net: row2
              column_net: col1
            top:
              row_net: row3
              column_net: col1
        ring:
          key:
            stagger: 0.65 ky
            spread: 19
            splay: -4
          rows:
            bottom:
              row_net: row5
              column_net: col3
            home:
              row_net: row1
              column_net: col3
            top:
              row_net: row2
              column_net: col3
              bind: 55
        middle:
          key:
            stagger: 0.4 ky
            spread: 19
            splay: -4
          rows:
            bottom:
              row_net: row1
              column_net: col2
            home:
              row_net: row6
              column_net: col4
            top:
              row_net: row1
              column_net: col4
        index:
          key:
            stagger: -0.4 ky
            spread: 18.5
            splay: -2
          rows:
            bottom:
              row_net: row4
              column_net: col5
            home:
              row_net: row5
              column_net: col5
            top:
              row_net: row6
              column_net: col5
        inner:
          key:
            stagger: -0.15 ky
            spread: kx
          rows:
            bottom:
              row_net: row3
              column_net: col6
            home:
              row_net: row3
              column_net: col2
            top:
              row_net: row5
              column_net: col6
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-0.35 kx, -1.1 ky]
      columns:
        near:
          key:
            spread: kx
            splay: -29
            rotate: 90
            origin: [-1 kx, -1 ky]
            column_net: P9
        home:
          key:
            spread: kx
            splay: -8
            rotate: 90
            origin: [-0.5 kx, -0.85 ky]
            column_net: P10
        far:
          key:
            spread: kx
            splay: -8
            rotate: 90
            origin: [-0.6 kx, -0.85 ky]
            column_net: P14
      rows:
        thumb:
          row_net: GND
#    thumbfantest1:
#      anchor:
#        ref: matrix_inner_bottom
#        shift: [-0.6 kx, -1.8 ky]
#      columns:
#        home:
#          key:
#            spread: kx
#            splay: -35
#            rotate: 90
#            origin: [0.55 kx, -3.55 ky]
#            column_net: P8
#        far:
#          key:
#            spread: kx
#            splay: -10
#            rotate: 90
#            origin: [-0.55 kx, -1.2 ky]
#            column_net: P9
#      rows:
#        thumb:
#          row_net: GND
outlines:
  # board dimensions according to JLCPCB: 122.28 mm x 101.05 mm
  raw:
    - what: rectangle
      where: true
      asym: source
      size: [kx + px, ky + py]
      corner: 2
  thumbfan_glue:
    - what: polygon
      points:
      - ref: matrix_inner_home
        shift: [0 kx, 0 ky]
      - ref: thumbfan_far_thumb
        shift: [0.7 kx, -0.5 ky]
      - ref: thumbfan_far_thumb
        shift: [0 kx - 3px, -0.5 ky - 0.5 py]
      - ref: matrix_pinky_bottom
        shift: [0.5 kx - 0.5 py, -0.5 ky - 0.5 py]
      - ref: matrix_pinky_home
      - ref: matrix_inner_home
  patch_outer:
    - what: polygon
      points:
        - ref: matrix_ring_top
        - ref: matrix_ring_bottom
        - ref: matrix_pinky_bottom
          shift: [-0.5 (kx + px), 0]
        - ref: matrix_pinky_top
          shift: [-0.5 (kx + px), 0]
  patch_inner:
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [0.5 (kx + px), 0]
        - ref: matrix_inner_bottom
          shift: [0.5 (kx + px), 0]
        - ref: matrix_index_bottom
        - ref: matrix_index_top
  controller_area:
    - what: rectangle
      where:
        - ref: matrix_inner_top
          # re-tranalte to new anchor position
          shift: [32/2 + 0 kx, 76.5/2 - 4.05 ky]
      size: [32, 76.5]
      corner: px
  switches:
    - what: rectangle
      where: true
      asym: source
      size: 14
  keycaps:
    - what: rectangle 
      where: true
      asym: source
      size: [kx, ky] 
  keycapspacing:
    - what: rectangle 
      where: true
      asym: source
      size: [kx+10, ky+10] 
      corner: 2
  thumb_home_spacing:
    - what: rectangle 
      where: thumbfan_home_thumb
      asym: source
      size: [kx*1.5, ky*1.7] 
  thumbcap_far:
    - what: rectangle 
      where: 
        - ref: thumbfan_far_thumb
          shift: [0, 0]
      size: [kx*2, ky] 
  thumbcap_home:
    - what: rectangle 
      where: 
        - ref: thumbfan_home_thumb
          shift: [0, 0]
      size: [kx*2, ky]
  thumbcap_near:
    - what: rectangle 
      where: 
        - ref: thumbfan_near_thumb
          shift: [0, 0]
      size: [kx*2, ky] 
  thumbcaps:
    - "thumbcap_far"
    - "+thumbcap_home"
    - "+thumbcap_near"
    - "+keycaps"
  thumb_far_spacing:
    - what: rectangle 
      where: thumbfan_far_thumb
      asym: source
      size: [kx*1.5, ky*1.5] 
      corner: 2
  switch4:
    - what: rectangle
      where:
        - ref: matrix_middle_bottom
          shift: [0, -28]
      asym: source
      size: 1.5 ky
      corner: 2
  keywell:
    - "raw"
    - "+patch_inner"
    - "+patch_outer"
    - "+keycapspacing"
    - "+thumbfan_glue"
    - "+thumb_home_spacing"
    - "+thumb_far_spacing"
    - "+switch4"
  base_outline:
    - "keywell"
    - "+controller_area"
  screw_holes:
    top_left:
      what: circle
      where:
        - ref: matrix_ring_top
          shift: [-0.55 kx, -0.25 ky]
      radius: 1.05
    bottom_left:
      what: circle
      where:
        - ref: matrix_pinky_bottom
          shift: [0.7 kx, 0]
      radius: 1.05
    top_right:
      what: circle
      where:
        - ref: matrix_inner_top
          shift: [-0.52 kx, -0.35 ky]
      radius: 1.05
    palm:
      what: circle
      where:
        - ref: matrix_index_bottom
          shift: [-0.15 ky, -0.8 ky]
      radius: 1.05
    thumb:
      what: circle
      where:
        - ref: thumbfan_far_thumb
          shift: [0 kx, 10]
      radius: 1.05
  mounting_holes:
    $extends: outlines.screw_holes
    top_left:
      radius: 1.05
    bottom_left:
      radius: 1.05
    top_right:
      radius: 1.05
    palm:
      radius: 1.05
    thumb:
      radius: 1.05
  bottom_outline:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-screw_holes"
  plate:
    - "keywell"
    - "-switches"
    - "-screw_holes"
  pcb:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-mounting_holes"
pcbs:
  top_plate:
    outlines:
      edge:
        outline: plate
        layer: Edge.Cuts
    footprints:
      jlc_order_number:
        what: text
        where:
          ref:
            - matrix_ring_home
          shift: [-0.25 kx, 0.5 ky]
        params:
          text: "JLCJLCJLCJLC"
          justify: left
  bottom_plate:
    outlines:
      edge:
        outline: bottom_outline
        layer: Edge.Cuts
  board:
    outlines:
      edge:
        outline: pcb
        layer: Edge.Cuts
    footprints:
      choc_hotswap:
        what: choc
        where:
          - /matrix_.*/
          - /thumbfan_.*/
        params:
          hotswap: true
          reverse: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{row_net}}"
      mcu_l:
        what: promicro
        where:
          ref:
            - matrix_inner_top
          shift: [20, -11]
          rotate: 270
        params:
          orientation: up
          P1: row1
          P2: row2
          P3: row3
          P4: row4
          P5: row5
          P6: row6
          P7: enc1
          P8: enc2
          P9: thumb1
          P10: thumb2
          P14: thumb3
          P15: col1
          P16: col2
          P18: col3
          P19: col4
          P20: col5
          P21: col6
      mcu_r:
        what: promicro
        where:
          ref:
            - matrix_inner_top
          shift: [22.5, -12.25]
          rotate: 270
        params:
          orientation: down
          P1: row1
          P2: row2
          P3: row3
          P4: row4
          P5: row5
          P6: row6
          P7: enc1
          P8: enc2
          P9: thumb1
          P10: thumb2
          P14: thumb3
          P15: col1
          P16: col2
          P18: col3
          P19: col4
          P20: col5
          P21: col6
      pad_plus:
        what: pad
        where:
          ref:
            - matrix_inner_top
          shift: [23, -6]
          rotate: 0
        params:
          front: true
          back: true
          width: 1.5
          height: 1.5
          text: "B+"
          net: Bplus
      pad_minus:
        what: pad
        where:
          ref:
            - matrix_inner_top
          shift: [23, -3]
          rotate: 0
        params:
          front: true
          back: true
          width: 1.5
          height: 1.5
          text: "B-"
          net: GND
      trrs:
        what: trrs_tight
        where:
          ref:
            - matrix_inner_bottom
          shift: [30, -11]
          rotate: 270
        params:
          reverse: true
          symmetric: false
          # The naming of the nets on this footprint is different from the Corne schematics.
          A: ""
          B: VCC
          C: GND
          D: P0
      jumper_l:
        what: jumper
        where:
          ref:
            - matrix_inner_bottom
          shift: [23.5, 0]
          rotate: 270
        params:
          side: B
          from: Bplus
          to: RAW
      jumper_r:
        what: jumper
        where:
          ref:
            - matrix_inner_bottom
          shift: [23.5, 0]
          rotate: 270
        params:
          side: F
          from: Bplus
          to: RAW
      slider_l:
        what: slider_threeway
        where:
          ref:
            - matrix_inner_bottom
          shift: [30, 0]
          rotate: 270
        params:
          side: F
          from: RAW
          left: Bplus
          right: ''
      slider_r:
        what: slider_threeway
        where:
          ref:
            - matrix_inner_bottom
          shift: [30, 0]
          rotate: 270
        params:
          side: B
          from: RAW
          left: ''
          right: Bplus
      encoder:
        what: rotary
        where: 
          ref: 
            - matrix_index_bottom	
          shift: [-0.5 kx, -1.5 ky]
          rotate: 90
        params:
          from: row2
          to: col4
          A: enc1
          B: enc2
          C: GND
      reset:
        what: reset_button
        where:
          ref:
            - matrix_inner_bottom
          shift: [17, 0]
          rotate: 270
        params:
          from: GND
          to: RST
      info_l:
        what: text
        where:
          ref:
            - matrix_pinky_bottom
          shift: [0.65 kx, -0.25 ky]
        params:
          text: "Zuuzboard v0.3"
          justify: left
      info_r:
        what: text
        where:
          ref:
            - matrix_pinky_bottom
          shift: [0.65 kx, -0.25 ky]
        params:
          layer: B.SilkS
          text: "Zuuzboard v0.3"
          justify: right mirror